/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.data.PackOutput
 *  net.minecraft.resources.ResourceLocation
 *  net.minecraft.sounds.SoundEvent
 *  net.minecraftforge.common.data.ExistingFileHelper
 *  net.minecraftforge.common.data.SoundDefinition
 *  net.minecraftforge.common.data.SoundDefinition$Sound
 *  net.minecraftforge.common.data.SoundDefinitionsProvider
 */
package com.barlinc.unusual_prehistory.datagen;

import com.barlinc.unusual_prehistory.UnusualPrehistory2;
import com.barlinc.unusual_prehistory.registry.UP2SoundEvents;
import java.util.function.Supplier;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.common.data.SoundDefinition;
import net.minecraftforge.common.data.SoundDefinitionsProvider;

public class UP2SoundDefinitionsProvider
extends SoundDefinitionsProvider {
    public UP2SoundDefinitionsProvider(PackOutput packOutput, ExistingFileHelper helper) {
        super(packOutput, "unusual_prehistory", helper);
    }

    public void registerSounds() {
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.AEGIROCASSIS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.AEGIROCASSIS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/hurt2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/hurt3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.AEGIROCASSIS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/idle4")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/idle5")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/idle6")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.AEGIROCASSIS_HOVER, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/aegirocassis/hover1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BARINASUCHUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/barinasuchus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/barinasuchus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BARINASUCHUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/barinasuchus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BARINASUCHUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/barinasuchus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/barinasuchus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/barinasuchus/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/barinasuchus/idle4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BARINASUCHUS_ATTACK, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/barinasuchus/bite1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BARINASUCHUS_THREATEN, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/barinasuchus/threaten1")).attenuationDistance(32));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BRACHIOSAURUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BRACHIOSAURUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BRACHIOSAURUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/idle4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BRACHIOSAURUS_ATTACK, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/attack1")).attenuationDistance(32));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BRACHIOSAURUS_STEP, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/step1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/step2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/step3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/step4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BRACHIOSAURUS_CALL, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/call1")).attenuationDistance(32), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/brachiosaurus/call2")).attenuationDistance(32));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.CARNOTAURUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/hurt1")).pitch(1.2f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.CARNOTAURUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.CARNOTAURUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/idle2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.CARNOTAURUS_STEP, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/step1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/step2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.CARNOTAURUS_ROAR, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/roar1")).pitch(0.9f).attenuationDistance(32));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.CARNOTAURUS_SNIFF, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/sniff1")).pitch(0.9f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.CARNOTAURUS_BITE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/bite1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/bite2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/bite3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.CARNOTAURUS_CHARGE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/charge1")).attenuationDistance(32));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.CARNOTAURUS_HEADBUTT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/headbutt1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.COELACANTHUS_HURT, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.COELACANTHUS_DEATH, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.COELACANTHUS_FLOP, UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop1").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop2").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop3").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop4").volume(0.3f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DESMATOSUCHUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/desmatosuchus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/desmatosuchus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DESMATOSUCHUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/desmatosuchus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DESMATOSUCHUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/desmatosuchus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/desmatosuchus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/desmatosuchus/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/desmatosuchus/idle4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DESMATOSUCHUS_STEP, UP2SoundDefinitionsProvider.sound((String)"mob/pig/step1").pitch(0.8f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step2").pitch(0.8f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step3").pitch(0.8f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step4").pitch(0.8f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step5").pitch(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DIMORPHODON_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dimorphodon/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dimorphodon/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DIMORPHODON_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dimorphodon/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DIMORPHODON_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dimorphodon/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dimorphodon/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dimorphodon/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dimorphodon/idle4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DIPLOCAULUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/diplocaulus/hurt1")).volume(0.5f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/diplocaulus/hurt2")).volume(0.5f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DIPLOCAULUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/diplocaulus/death1")).volume(0.5f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DIPLOCAULUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/diplocaulus/idle1")).volume(0.17f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/diplocaulus/idle2")).volume(0.17f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/diplocaulus/idle3")).volume(0.17f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/diplocaulus/idle4")).volume(0.17f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DIPLOCAULUS_STEP, UP2SoundDefinitionsProvider.sound((String)"mob/frog/step1").pitch(0.95f), UP2SoundDefinitionsProvider.sound((String)"mob/frog/step2").pitch(0.95f), UP2SoundDefinitionsProvider.sound((String)"mob/frog/step3").pitch(0.95f), UP2SoundDefinitionsProvider.sound((String)"mob/frog/step4").pitch(0.95f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DROMAEOSAURUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dromaeosaurus/hurt_0")).volume(0.8f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dromaeosaurus/hurt_1")).volume(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DROMAEOSAURUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dromaeosaurus/death_0")).volume(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DROMAEOSAURUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dromaeosaurus/idle_0")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dromaeosaurus/idle_1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dromaeosaurus/idle_2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DROMAEOSAURUS_EEPY, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dromaeosaurus/sleep_0")).volume(0.7f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dromaeosaurus/sleep_1")).volume(0.7f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DUNKLEOSTEUS_HURT, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DUNKLEOSTEUS_DEATH, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DUNKLEOSTEUS_FLOP, UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop1").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop2").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop3").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop4").volume(0.3f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.SMALL_DUNKLEOSTEUS_BITE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dunkleosteus/small_bite1")).volume(0.7f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEDIUM_DUNKLEOSTEUS_BITE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dunkleosteus/medium_bite1")).volume(0.9f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LARGE_DUNKLEOSTEUS_BITE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/dunkleosteus/large_bite1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.HIBBERTOPTERUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/hibbertopterus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/hibbertopterus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.HIBBERTOPTERUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/hibbertopterus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.HIBBERTOPTERUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/hibbertopterus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/hibbertopterus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/hibbertopterus/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/hibbertopterus/idle4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.HIBBERTOPTERUS_STEP, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/hibbertopterus/step1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/hibbertopterus/step2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.JAWLESS_FISH_HURT, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.JAWLESS_FISH_DEATH, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.JAWLESS_FISH_FLOP, UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop1").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop2").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop3").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop4").volume(0.3f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KAPROSUCHUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kaprosuchus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kaprosuchus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KAPROSUCHUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kaprosuchus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kaprosuchus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kaprosuchus/idle3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KAPROSUCHUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kaprosuchus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KENTROSAURUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kentrosaurus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kentrosaurus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KENTROSAURUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kentrosaurus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KENTROSAURUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kentrosaurus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kentrosaurus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kentrosaurus/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kentrosaurus/idle4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KENTROSAURUS_STEP, UP2SoundDefinitionsProvider.sound((String)"mob/camel/step1").volume(0.45f).pitch(0.9f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step2").volume(0.45f).pitch(0.9f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step3").volume(0.45f).pitch(0.9f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step4").volume(0.45f).pitch(0.9f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step5").volume(0.45f).pitch(0.9f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step6").volume(0.45f).pitch(0.9f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KIMMERIDGEBRACHYPTERAESCHNIDIUM_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kimmeridgebrachypteraeschnidium/hurt1")).pitch(1.4f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kimmeridgebrachypteraeschnidium/hurt2")).pitch(1.4f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KIMMERIDGEBRACHYPTERAESCHNIDIUM_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kimmeridgebrachypteraeschnidium/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KIMMERIDGEBRACHYPTERAESCHNIDIUM_LOOP, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kimmeridgebrachypteraeschnidium/loop1")).volume(0.6f).attenuationDistance(8));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KIMMERIDGEBRACHYPTERAESCHNIDIUM_NYMPH_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kimmeridgebrachypteraeschnidium/hurt1")).pitch(2.0f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kimmeridgebrachypteraeschnidium/hurt2")).pitch(2.0f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.KIMMERIDGEBRACHYPTERAESCHNIDIUM_NYMPH_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kimmeridgebrachypteraeschnidium/death1")).pitch(1.5f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LEPTICTIDIUM_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/leptictidium/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/leptictidium/hurt2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/leptictidium/hurt3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LEPTICTIDIUM_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/leptictidium/death1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/leptictidium/death2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LEPTICTIDIUM_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/leptictidium/idle1")).volume(0.8f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/leptictidium/idle2")).volume(0.8f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/leptictidium/idle3")).volume(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LYSTROSAURUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/hurt1")).pitch(0.9f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/hurt2")).pitch(0.9f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/hurt3")).pitch(0.9f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/hurt4")).pitch(0.9f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/hurt5")).pitch(0.9f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LYSTROSAURUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/death1")).pitch(0.9f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/death2")).pitch(0.9f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/death3")).pitch(0.9f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LYSTROSAURUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/idle4")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/idle5")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/idle6")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/idle7")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LYSTROSAURUS_STEP, UP2SoundDefinitionsProvider.sound((String)"mob/pig/step1").pitch(0.9f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step2").pitch(0.9f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step3").pitch(0.9f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step4").pitch(0.9f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step5").pitch(0.9f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LYSTROSAURUS_CHAINSMOKER, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/cough1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/cough2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/lystrosaurus/cough3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MAJUNGASAURUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/majungasaurus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/majungasaurus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MAJUNGASAURUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/majungasaurus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MAJUNGASAURUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/majungasaurus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/majungasaurus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/majungasaurus/idle3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MAJUNGASAURUS_ATTACK, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/majungasaurus/attack1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MAJUNGASAURUS_SNIFF, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/sniff1")).pitch(1.2f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MAJUNGASAURUS_STEP, UP2SoundDefinitionsProvider.sound((String)"mob/camel/step1").volume(0.4f).pitch(0.8f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step2").volume(0.4f).pitch(0.8f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step3").volume(0.4f).pitch(0.8f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step4").volume(0.4f).pitch(0.8f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step5").volume(0.4f).pitch(0.8f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step6").volume(0.4f).pitch(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MANIPULATOR_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/hurt2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/hurt3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MANIPULATOR_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MANIPULATOR_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/idle4")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/idle5")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MANIPULATOR_STEP, UP2SoundDefinitionsProvider.sound((String)"mob/spider/step1").pitch(0.85f), UP2SoundDefinitionsProvider.sound((String)"mob/spider/step2").pitch(0.85f), UP2SoundDefinitionsProvider.sound((String)"mob/spider/step3").pitch(0.85f), UP2SoundDefinitionsProvider.sound((String)"mob/spider/step4").pitch(0.85f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MANIPULATOR_ATTACK_VOCAL, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/attack_vocal1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/attack_vocal2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MANIPULATOR_ATTACK_SLASH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/attack_slash1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/manipulator/attack_slash2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEGALANIA_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/hurt1")).pitch(0.9f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/hurt2")).pitch(0.9f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEGALANIA_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/death1")).pitch(0.9f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/death2")).pitch(0.9f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEGALANIA_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/idle1")).pitch(0.8f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/idle2")).pitch(0.8f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/idle3")).pitch(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEGALANIA_ROAR, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/roar1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEGALANIA_STEP, UP2SoundDefinitionsProvider.sound((String)"mob/camel/step1").volume(0.5f).pitch(0.87f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step2").volume(0.5f).pitch(0.87f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step3").volume(0.5f).pitch(0.87f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step4").volume(0.5f).pitch(0.87f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step5").volume(0.5f).pitch(0.87f), UP2SoundDefinitionsProvider.sound((String)"mob/camel/step6").volume(0.5f).pitch(0.87f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEGALANIA_TAIL_SWING, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/tail_swing1")).volume(0.9f).pitch(0.9f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/tail_swing2")).volume(0.9f).pitch(0.9f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEGALANIA_BITE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/bite1")).volume(0.8f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/bite2")).volume(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEGALANIA_JUMPSCARE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/megalania/jumpscare1")).attenuationDistance(20));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.METRIORHYNCHUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.METRIORHYNCHUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.METRIORHYNCHUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/idle4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.METRIORHYNCHUS_BITE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/bite1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/bite2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.METRIORHYNCHUS_BELLOW, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/metriorhynchus/bellow1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.ONCHOPRISTIS_HURT, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.ONCHOPRISTIS_DEATH, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.ONCHOPRISTIS_FLOP, UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop1").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop2").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop3").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop4").volume(0.3f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PACHYCEPHALOSAURUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PACHYCEPHALOSAURUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PACHYCEPHALOSAURUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/idle4")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/idle5")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PACHYCEPHALOSAURUS_WARN, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/warn1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PACHYCEPHALOSAURUS_BONK, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pachycephalosaurus/bonk1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PACHYCEPHALOSAURUS_STEP, UP2SoundDefinitionsProvider.sound((String)"mob/pig/step1").pitch(0.85f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step2").pitch(0.85f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step3").pitch(0.85f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step4").pitch(0.85f), UP2SoundDefinitionsProvider.sound((String)"mob/pig/step5").pitch(0.85f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PRAEPUSA_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/praepusa/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/praepusa/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PRAEPUSA_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/praepusa/death1")).pitch(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PRAEPUSA_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/praepusa/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/praepusa/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/praepusa/idle3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PRAEPUSA_MITOSIS, UP2SoundDefinitionsProvider.sound((String)"mob/slime/attack1").pitch(1.3f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/attack2").pitch(1.3f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PRAEPUSA_BOUNCE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/praepusa/bounce1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PSILOPTERUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PSILOPTERUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/hurt2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/hurt3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PSILOPTERUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/idle4")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/idle5")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PSILOPTERUS_BITE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/bite1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/bite2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/bite3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PSILOPTERUS_ATTACK, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/attack1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/attack2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/attack3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PSILOPTERUS_CALL, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/psilopterus/call1")).attenuationDistance(24));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PTERODACTYLUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pterodactylus/hurt1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PTERODACTYLUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pterodactylus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.PTERODACTYLUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pterodactylus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pterodactylus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/pterodactylus/idle3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.STETHACANTHUS_HURT, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.STETHACANTHUS_DEATH, UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt1"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt2"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt3"), UP2SoundDefinitionsProvider.sound((String)"entity/fish/hurt4"));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.STETHACANTHUS_FLOP, UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop1").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop2").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop3").volume(0.3f), UP2SoundDefinitionsProvider.sound((String)"entity/fish/flop4").volume(0.3f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.STETHACANTHUS_BITE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/stethacanthus/bite1")).volume(0.6f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TALPANAS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/talpanas/hurt1")).volume(0.8f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/talpanas/hurt2")).volume(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TALPANAS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/talpanas/death1")).volume(0.8f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/talpanas/death2")).volume(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TALPANAS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/talpanas/idle1")).volume(0.8f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/talpanas/idle2")).volume(0.8f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TELECREX_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/telecrex/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/telecrex/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TELECREX_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/telecrex/death1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/telecrex/death2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TELECREX_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/telecrex/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/telecrex/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/telecrex/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/telecrex/idle4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.THERIZINOSAURUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/hurt1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/hurt2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.THERIZINOSAURUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.THERIZINOSAURUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/idle3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.THERIZINOSAURUS_ATTACK, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/attack1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/attack2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/attack3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.THERIZINOSAURUS_STEP, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/step1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/step2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/step3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.THERIZINOSAURUS_ROAR, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/roar1")).attenuationDistance(32), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/roar2")).attenuationDistance(32));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.THERIZINOSAURUS_NOTICE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/notice1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/therizinosaurus/notice2")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.ULUGHBEGSAURUS_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/ulughbegsaurus/hurt1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.ULUGHBEGSAURUS_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/ulughbegsaurus/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.ULUGHBEGSAURUS_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/ulughbegsaurus/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/ulughbegsaurus/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/ulughbegsaurus/idle3")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.ULUGHBEGSAURUS_ATTACK, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/ulughbegsaurus/bite1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.ULUGHBEGSAURUS_STEP, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/step1")).pitch(1.13f).volume(0.6f), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/carnotaurus/step2")).pitch(1.13f).volume(0.6f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.UNICORN_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/unicorn/hurt1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.UNICORN_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/unicorn/death1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.UNICORN_IDLE, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/unicorn/idle1")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/unicorn/idle2")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/unicorn/idle3")), UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/unicorn/idle4")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LIVING_OOZE_HURT, UP2SoundDefinitionsProvider.sound((String)"mob/slime/big1").pitch(1.15f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big2").pitch(1.15f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big3").pitch(1.15f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big4").pitch(1.15f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LIVING_OOZE_DEATH, UP2SoundDefinitionsProvider.sound((String)"mob/slime/big1").pitch(1.1f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big2").pitch(1.1f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big3").pitch(1.1f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big4").pitch(1.1f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LIVING_OOZE_SQUISH, UP2SoundDefinitionsProvider.sound((String)"mob/slime/big1").pitch(1.15f).volume(0.5f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big2").pitch(1.15f).volume(0.5f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big3").pitch(1.15f).volume(0.5f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big4").pitch(1.15f).volume(0.5f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LIVING_OOZE_JUMP, UP2SoundDefinitionsProvider.sound((String)"mob/slime/big1").pitch(1.15f).volume(0.5f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big2").pitch(1.15f).volume(0.5f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big3").pitch(1.15f).volume(0.5f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/big4").pitch(1.15f).volume(0.5f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.LIVING_OOZE_SPIT, UP2SoundDefinitionsProvider.sound((String)"mob/slime/attack1").pitch(1.1f).volume(0.5f), UP2SoundDefinitionsProvider.sound((String)"mob/slime/attack2").pitch(1.1f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TRANSMOGRIFIER_LOOP, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("block/transmogrifier/loop1")).attenuationDistance(8).volume(0.7f).pitch(0.78f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TRANSMOGRIFIER_START, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("block/transmogrifier/start1")).attenuationDistance(10));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TRANSMOGRIFIER_STOP, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("block/transmogrifier/stop1")).attenuationDistance(10));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TAR_POP, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("block/tar/pop1")));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.DOOMSURF_DISC, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("music/doomsurf_disc")).stream());
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.MEGALANIA_DISC, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("music/megalania_disc")).stream());
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.TARIFYING_DISC, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("music/tarifying_disc")).stream());
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BUG_HURT, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kimmeridgebrachypteraeschnidium/death1")).pitch(1.75f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BUG_DEATH, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/kimmeridgebrachypteraeschnidium/death1")).pitch(1.75f));
        this.sound((Supplier<SoundEvent>)UP2SoundEvents.BUG_BUZZ, UP2SoundDefinitionsProvider.sound((ResourceLocation)UnusualPrehistory2.modPrefix("entity/ambient/bug_buzz1")).attenuationDistance(4));
    }

    private void soundDefinition(Supplier<SoundEvent> soundEvent, String subtitle, SoundDefinition.Sound ... sounds) {
        this.add(soundEvent.get(), SoundDefinition.definition().subtitle("subtitles." + subtitle).with(sounds));
    }

    private void sound(Supplier<SoundEvent> soundEvent, SoundDefinition.Sound ... sounds) {
        this.soundDefinition(soundEvent, soundEvent.get().m_11660_().m_135815_(), sounds);
    }
}

